4.2.1 inline form
thinknetica-django-lab-02/dpodd pull request #41
Opened 2021-04-06 02:05 UTC by dpodd

Closes #30

2021-04-08 01:59 UTC, dpodd commented on marketplace/apps/profiles/views.py
> +    def get_object(self, request):
А зачем мы здесь явно передаем request как позиционный аргумент, ведь он по умолчанию он в CBV хранится в self.request. Мне этот момент не очень понятен.

2021-04-08 22:02 UTC, morgangt commented
Вам не нужно передавать одним аргументом request достаточно `def get_object(self):` либо `def get_object(self, queryset=None):` - когда наследуемся например от UpdateView

2021-04-08 22:14 UTC, morgangt requested changes
есть несколько моментов которые стоит исправить

2021-04-08 22:14 UTC, morgangt commented on marketplace/apps/main/views.py
> +from .models import Goods, Tag
правильнее было бы указывать полный адрес модуля `from apps.main.models import Goods, Tag`
но ваш вариант более универсальный в плане если захотите часть кода использовать в другом проекте

2021-04-08 22:14 UTC, morgangt commented on marketplace/apps/main/views.py
> +    paginate_by = 10
у всех классов должен быть docstring пусть хотя бы короткий например с указанием страницы которую генерит этот CBV

2021-04-08 22:14 UTC, morgangt commented on marketplace/apps/main/views.py
> +        for q in q_list:
однобуквенные переменные использовать плохо, надо более осознано подбирать имена переменным 
например в данном случае tags_name вместо q_list и tag вместо q

2021-04-08 22:14 UTC, morgangt commented on marketplace/apps/profiles/views.py
> +    model = User
нужно добавить docstring

2021-04-08 22:14 UTC, morgangt commented on marketplace/apps/profiles/views.py
> +        """Validate the inline form and save both forms provided."""
немного странно такую валидацию разбивать на разные методы, но если так удобнее то - хорошо, НО предлагаю пересмотреть название метода, предлагаю оставить просто valid_formset так как метод в названии которого есть form который находиться во view сильно путает

2021-04-08 22:14 UTC, morgangt commented on marketplace/apps/profiles/views.py
> +        return request.user
здесь можно совсем убрать этот метод , он будет унаследован от родительского класса UpdateView

2021-04-09 01:41 UTC, dpodd commented on marketplace/apps/profiles/views.py
> +        return request.user
да, но в данном конкретном случае это оправданно, ибо экономит один лишний запрос в базу. Ведь у нас уже есть объект user в request, зачем ходить туда еще раз?
Метод оставил, но уточнил docstring, проясняющий это.

2021-04-09 01:59 UTC, dpodd commented on marketplace/apps/profiles/views.py
> +        """Validate the inline form and save both forms provided."""
насчет "странно" - так это официальное решение, ссылку на которое мне дал Михаил. https://gist.github.com/mikhailborodin/b54a732a3bdf87c590c5b76c65c5f45f :)
Я к нему добавил только messages и все (правда, как я писал вам в телеграмме, в нем я нашел ошибку, но исправления внес в следующем pr 4.3).

насчет названия соглашусь, что оно путает. Не соглашусь с предложенным вариантом. Лучше оставить просто form_valid / form_invalid - мы ведь ветвим код исходя из результатов проверки основой формы и эти методы по дефолту в джанге. А еще одна проверка formset.is_valid - ее уже сделать внутри метода form_valid.

2021-04-09 15:41 UTC, morgangt commented on marketplace/apps/profiles/views.py
> +        return request.user
на самом деле django внутри себя делает этот один запрос в БД за объектом user, request в djnago это объект запроса который сделал нам клиент, тоесть этот объект отражает http запрос, в django на уровне middleware добавляет свои свойства и методы чтобы нам было проще работать. 

По итогу в request сначала храниться только cookie по которой определяем user и достаем его из БД, на уровне middleware. В целом все запросы к бд можно отследить с помощью плагина django toolbar

2021-04-09 15:43 UTC, morgangt commented on marketplace/apps/profiles/views.py
> +        """Validate the inline form and save both forms provided."""
давайте изменим хотя бы на formset_valid

2021-04-09 22:21 UTC, dpodd commented on marketplace/apps/profiles/views.py
> +        return request.user
Спасибо 👍

2021-04-10 00:21 UTC, dpodd commented on marketplace/apps/profiles/views.py
> +        return request.user
Убрать его не получилось по другой причине: у нас ссылка на профиль вида `/accounts/profile` - не ни pk, ни slug.
Без них стандартный `get_object` не знает, что брать из базы.

2021-04-10 00:41 UTC, dpodd commented on marketplace/apps/profiles/views.py
> +        """Validate the inline form and save both forms provided."""
Может я снова чего-то не понял? 🤷‍♂️

Смотрите, у нас есть две формы: form и formset. Нам нужно, одна за другой, провести две проверки на валидность, вызывав у каждой метод `.is_valid()`. Проверка первой формы, основной, реализована по умолчанию в Джанге. 
В методе post: 

```form = self.get_form()
if form.is_valid():
    return self.form_valid(form)
else:
    return self.form_invalid(form)
```

то есть у нас есть форма `form`, и название метода, который  вызывается после, **складывается из названия формы ("form") и результата выполнения метода `form.is_valid()` ("valid"/"invalid")**. То есть `form_valid` следует читать не как "валидировать форму", а как "здесь лежит код, который нужно выполнить, если форма валидна".

Далее, по коду. Где проводить проверку второй формы formset? Очевидно, в методах `form_valid` и `form_invalid`. И вот там, **по аналогии**, можно вызывать методы 

```
if form2.is_valid():
    return self.form2_valid(form1, form2)
else:
    return self.form2_invalid(form1, form2)
```

Вот. Примерно так. Ну и инстансы всех форм передаем на следующий уровень обработки, чтобы правильно рендерить форму.

Вообще, с формами классное задание. Я стал лучше понимать, почему на некоторых сайтах с формами такой плохой юзер экспириенс. Чем более сложная форма, тем быстрее растет сложность кода, ведь нужно стараться, чтобы несколько форм вели себя как одна целая для пользователя.

Пока писал это, переписал решение опять, сделал его красивее и короче, решил, что метод post переопределять вообще не надо )

2021-04-10 10:08 UTC, morgangt approved these changes

2021-04-10 12:05 UTC, merged