7.5 External API
thinknetica-django-lab-02/dpodd pull request #85
Opened 2021-04-26 15:23 UTC by dpodd

Closes #50

2021-04-27 09:42 UTC, morgangt requested changes

2021-04-27 09:42 UTC, morgangt commented on marketplace/apps/main/tasks.py
> +        print(f"Message failed with error: {responseData['messages'][0]['error-text']}")
Уберите print

2021-04-27 09:42 UTC, morgangt commented on marketplace/apps/main/tasks.py
> +    code = random.randint(1000, 9999)
Предлогом подумать в этом месте над тем чтобы заменить БД для хранения code, на Redis 
БД дорого хранить code, тем более их надо будет удалить после определенного периода, тем более пользователи могут массово регестрироваться и запрашивать коды.
Если кода хранить в Redis тогда можно сохранять пару ключ-значение в Redis где ключ будет сам код с каким-то префиксом например f"sms_code{code}" а значение будет id user чтобы понимать что данный код именно для этого пользователя. Плюс в Redis записи можно хранить по времени указывать ttl - время жизни (https://redis.io/commands/TTL)

Но это лишь предложение по улучшению, вы можете и дальше использовать БД

2021-04-27 09:42 UTC, morgangt commented on marketplace/apps/main/models.py
> +    response = models.JSONField(verbose_name="json response from SMS provider")
нет времени создания кода, без времени созданиях мы не сможем удалять старые записи, тем более мы не сможем сказать user что код который он ввел устарел, поесть user сможет перебором угадать код

2021-04-27 10:14 UTC, dpodd commented on marketplace/apps/main/tasks.py
> +    code = random.randint(1000, 9999)
А как это реализовать?
В частности, как существующая модель будет совместима с новым хранилищем? Удалить существующую модель и создать свой класс, который реализует методы save_sms() и retrieve_sms() ? Или просто переписать метод save() в существующей модели? Или как-то иначе?

2021-04-27 10:21 UTC, morgangt commented on marketplace/apps/main/tasks.py
> +    code = random.randint(1000, 9999)
Лучше ни как не завязываться на модель, просто сделать два метода которые будут работать с Redis один будет записывать код и выставлять время жизни этого кода, второй метод будет принимать код введенный пользователем и в ответ возвращать true or false в зависимости от того есть есть этот код в reids или нет 
И эти методы можно реализовать как методы для модели profile

2021-04-27 11:47 UTC, dpodd commented on marketplace/apps/main/tasks.py
> +    code = random.randint(1000, 9999)
Ну у меня же была просто тестовая таска для отправки единичного смс на свой собственный номер, а вы предлагаете целую систему верификации номеров пользователей придумать, с интерфейсом. Если я правильно понял.

Это надо переделывать много чего в коде, отдельную view писать для ввода кода верификации и т.п. Не, я не против, но тогда я хотел бы уточнить фронт работ и увидеть bigger picture.

1) создаем два url, скажем /accounts/send_verification_code и /accounts/verify_code. В первом url  - просто отображается кнопка, которая будет отправлять post запрос на  /accounts/send_verification_code. Во view обрабатываем этот запрос - создаем таску в celery - она создает код, записывает сгенерированный код в редисе, отправляет смс. Потом view редиректит на url  /accounts/verify_code - в котором отображается форма с полем ввода пришедшего кода и кнопкой "отправить код". В соответсвующем view обрабатываем post запрос - ходим в редис, сравниваем сохраненный код с введенным.

Если все ок - ставим True в поле Profile.verified_phone (модель придется расширить). Если не ок - возврашаем форму с ошибкой.

2) дополнительные методы для редиса создаем в модели Profile.
3) непонятна судьба модели SMSLog. Она, получается, не нужна?

2021-05-05 16:16 UTC, morgangt approved these changes

2021-05-05 16:19 UTC, morgangt commented on marketplace/apps/main/tasks.py
> +    code = random.randint(1000, 9999)
Всю систему вокруг верификации пользователя можно реализовать в другом pr но о ней стоит как минимум задуматься 
1. Да, вы все верно описали 
2. Да
3. SMSLog я бы заменил на Redis

2021-05-06 13:08 UTC, merged